#include <iostream>
#include "matriz.h"
#include "prog.h"
using namespace std;

int main() {

	/*
	Matrix m("TGTTGTCACTTATGCGTGCTGGGCAGGCTGAGATAGATCCGACAC","TGATGTATTAGGACCTCAACACAAGAAGGAAATTATTCGATATTTGTATAATCATCAGAACGAAGATGGGGGTTGGGGATTCC");

	m.local();

	//m.print();
	//cout << endl;
	//m.print2();
	m.caminoL();
	m.pr_camino();

	//cout << m.data[m.data.size() - 1][m.data[0].size() - 1].first << endl;

	*/

	vector<string> doc;

	doc.push_back("TCAGAAATGTCAGATGATCTAGTTGGGGCAAAAATGGAAACAGAGCAATTCTATGATGCTGTTAATGTCATCCTCTCTCTACAA");
	doc.push_back("AGAACATGAGGAGATTGAAAGGATGCGCCAAGAATTCACCAAAAATCGATTCTCCATCAAACAAAGTGCAGACCTCTTGATGAG");
	doc.push_back("TCTTTTCAGAAAGCTATACCCGAAGCATAGGCGAAAGGAAATAGATCGCTGCATTTCCAAAGCAATCCGATACATTGAAAACAC");
	doc.push_back("GCAGAAGATGGCTTGAAAATCCAGAGTTTTGGCTGCCAAATGTGGGATGCAGCATTTGCTATTCAAGCAATACTGAGTGGTAATGTGAG");
	doc.push_back("GAAAAGGTAACTGCAGAAGCATTGATCACTACAATTAGAAGGTCCATCACCTTTTATTCTTCAATTCAAGCCCATGATGGCCACTGGCCTGCTGAATCT");
	doc.push_back("GGGATTTCTTCATCATGTGGGAGAGCGTGTTCTGAACACTTGGCCATTTTCAATGCTAAGACAGAAGGCAATAGAAGTTGCTATTAATCATGTACGTTACG");
	doc.push_back("TACAGGAGTATTTATGAGGAACTGTACCCTAAACTACTCATCATATCGAAACATCTTTCCTATATGGGCTCTTGGAGAGTACCGTCGCAGAGTCTTATGTGCATGA");


	Prog c(doc);
	//c.mat_dist();
	c.prog_total();

	system("pause");
	return 0;
}